config/routes.rb
Rails.application.routes.draw do
  get 'user/new'

  root 'main#index'

  resource :session, only: [:new, :create, :destroy]

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  get 'signup' => 'user#new'

  get 'wechat', to: 'wechat#show'
  get 'wechat/menu', to: 'wechat#menu'
  post 'wechat', to: 'wechat#create'



end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false}

  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end
end

app/controllers/wechat_controller.rb
class WechatController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :check_weixin_legality

  #验证WeChat接口
  def show
    puts "get show"
    render :text => params[:echostr]
  end

  #处理微信服务器发来的消息
  def create
    puts "get create"
    @req = Hash.from_xml(request.raw_post).symbolize_keys[:xml]

    case @req["MsgType"]
    when "text"
      @req["msg_type"] = "text"
      @req["response_text"] = "功能正在开发当中，敬请期待..."
      render "res", formats: :xml
    when "event"
      @req["msg_type"] = "text"
      @req["response_text"] = "欢迎关注账号，这是发自开发者的一段代码"
      render "res", formats: :xml
    end
  end

  def menu
    puts 'get menu'
    access_token = $redis.get('access_token') || get_access_token

    
  end

  private
  def check_weixin_legality
    puts "get here1"
    array = [Rails.configuration.wechat_token, params[:timestamp], params[:nonce]].sort
    render :text => "Forbidden", :status => 403 if params[:signature] != Digest::SHA1.hexdigest(array.join)
  end

  def get_access_token
    puts 'get_access_token'
    require 'net/http'
    uri = URI("https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=#{Rails.configuration.wechat_appid}&secret=#{Rails.configuration.wechat_appsecret}")
    res = Net::HTTP.get(uri)
    res = JSON.parse(res)

    $redis.set('access_token', res.access_token)
    $redis.set('access_token_expired_time', res.expires_in)

    res.access_token
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timeline</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <h3>这里是主页</h3>
  <%= link_to "login", login_path %>
  <%= link_to "signup", signup_path %>
</body>
</html>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/wechat/res.xml.erb
<xml>
<ToUserName><![CDATA[<%= @req["FromUserName"] %>]]></ToUserName>
<FromUserName><![CDATA[<%= @req["ToUserName"] %>]]></FromUserName>
<CreateTime><%= Time.now.to_i %></CreateTime>
<MsgType><![CDATA[<%= @req["msg_type"] %>]]></MsgType>
<Content><![CDATA[<%= @req["response_text"] %>]]></Content>
</xml>